modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
    modId="acaciaddon"
    version="${version}"
    displayName="AcaciAddon"
    logoFile="logo.png"
    credits="<3"
    authors="Gamaaaa & MrEliott35"
    description='''
This mod is a part of the ModulProject

The objective : Create a new difficulty with the Acacia Tree, with the AcaciAxe you can cut so much tree.
'''

[[dependencies.aciacaddon]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.aciacaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
